apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-actions-gke
  template:
    metadata:
      labels:
        app: github-actions-gke
    spec:
      containers:
        - name: app
          user:
            exec:
              apiVersion: client.authentication.k8s.io/v1beta1
              command: gke-gcloud-auth-plugin
              installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
                https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
              provideClusterInfo: true
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always